---
name: 'shellcheck'
description: 'shellcheck by Pipeline Components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: .
  options:
    description: 'Additional options'
    required: false
    default: ''
runs:
  using: 'docker'
  image: docker://pipelinecomponents/shellcheck
  args:
    - shellcheck
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
